### ISSUE TITLE
Last commit of dependency package (rc-trigger) breaks the dropdown

### ISSUE THREAD

**Issue by 1i1it** [react-component/dropdown#24]
Hi, 
It seems that you have a dependency on https://github.com/react-component/trigger, and the following commit breaks the dropdown (namely prevents it from opening, the div with the dropdown gets position 'absolute' and style.top/left of '-9999px'. 
https://github.com/react-component/trigger/commit/6ea92c72a8ed03911ebb7bcf3db9700b22f230e6

At the same time the requirement for rc-trigger dependency is "1.x", which causes npm to install the latest (broken) version 1.8.2.
I suggest updating  rc-trigger dependency to "1.8.1", as this was the last working version and fixing the rc-trigger.
Should I create a pull request?
Thanks! :)

**Comment by benjycui** [comment]
Trace: https://github.com/react-component/trigger/pull/43

**Comment by afc163** [comment]
Reinstall node_modules

**Comment by mystetskyivlad** [comment]
But the problem with variable dependency (1.x) that it can happen again, when rc-trigger or any other dependency will publish breakable change - users of rc-dropdown will be affected by it.
We are using rc-dropdown all across our application and it was broke up because of this, so we are suggesting to set up specific WORKING and CHECKED version of rc-trigger dependency (f.e. 1.9.0 if last fix is working) and each time when you/we will want to update version of rc-trigger, we can change it explicitly with all checks.

**Comment by afc163** [comment]
fixed in rc-trigger@1.8.3
